pytroll/trollflow2

examples/pl.yaml
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This PR makes the plugins configurable without passing the config items via kwargs at initialization.
- The config values can be given in the product list
- The plugins can have internal defaults which will be used if no config can be found
- The settings can be at different levels of the config, e.g. each of the areas can have different resampling settings

Make plugins configurable

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

With this PR it's possible to replace input metadata values with aliases. This can be used e.g. to replace platform name with the OSCAR version and `AVHRR/3` sensor name to `avhrr-3` that SatPy understands.

Add a plugin to update input metadata with aliases

---

examples/pl.yaml
setup.py
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This PR makes it possible to define minimum and maximum Sun zenith angles (SZA) for each product:
- Set `sunzen_check_lon` and `sunzen_check_lat` to define the location where to check the SZA
- Set `sunzen_maximum_angle` for daytime product to tell the maximum allowed SZA
- Set `sunzen_minimum_angle` for nighttime product to tell the minimum required SZA
The settings can be either at:
- `product` level to control settings for individual product
- `area` level to have the settings for all the products in that area group
- in `common` to have global settings for each area and product

Add Sun zenith angle filtering

---

bin/satpy_launcher.py
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This PR adds a plugin that aborts processing of the scene if the platrom name isn't in the list of processed platforms.

Add a plugin to check platform name

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds support for the `null` area, representing data in satellite projection (that is data that will not be resampled).

Add support for products in satellite projection

---

trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This PR exposes three more keyword arguments for `scn.resample()`:
- `cache_dir`: store resampling look-up-tables to this directory (default: `None`, don't save them)
- `mask_area`: force masking for invalid data locations (default: `False`, don't mask data)
- `epsilon`: allowed resampling uncertainty in meters (default: `0`)
Also adds a possibility to use `use_min_area` and `use_max_area` to do the equivalent of `scn.resample(scn.min_area())` and `scn.resampler(scn.max_area())`

Expose more kwargs for scn.resample()

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

The expand function in laucher.py was not py3 compatible and obviously not tested. This is now fixed.

Fix and test the expand function

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

Add support for passing a `resolution` parameter to the scene loading through adding it to the `common` section of the product list

Add support for passing a `resolution` parameter to the scene loading

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This PR makes it possible to delay composite creation until after resampling. In most cases this is much faster, and is thus is now the default behaviour. To create composites _before_ resampling the user can set `delay_composites: False` in the `common` section of the production config file.
As an example, 5-area 55-product product list with bilinear interpolation and pre-computed resampling LUTs the processing times (with a single core) are:
- `delay_composites: False`: 35 minutes
- `delay_composites: True`: 5 minutes

Make it possible to delay composite creation

---

trollflow2/launcher.py

Pyyaml 5.1 changed default behaviour of `yaml.load()` so that automatic imports using `!!python/name:package.module.function` don't work anymor. This PR adds a fix and backwards compatibility for the changes.
More info: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Fix compatibility issues caused by changes introduced in pyyaml 5.1

---

README.md
setup.py
trollflow2/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR makes it possible to use `trollsift` patterns in the publisher topics. All the keys in passed to the message can be used.

Make publish topic composable

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds a check that `collection_area_id`, if exists, in input metadata matches the areas in the product list. This is useful when polar data are collected using `gatherer.py`. With this the collections are processed only for the proper areas. For best effect all the areas should have different priorities.

Check `collection_area_id` in the input metadata

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds a feature for embedding "overviews" to the saved TIFF images.

Add overviews to output images

---

trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_trollflow2.py

Some times input metadata has values in a list, tuple or set (e.g. "sensor"). These values were not aliased properly earlier, and this PR fixes those cases.

Handle aliases for iterable metadata values

---

examples/pl.yaml
trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

As Trollflow2 handles crashes internally, `supervisord` don't report anything about them, and only trace of the problem is in the log files. This PR adds a possibility to send emails with the error message.

Add a possibility to send emails about crashes

---

trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

Trollstalker/gatherer/etc. may have multiple sensors defined in the metadata as a list, set or tuple. This PR takes only one of the sensors when estimating the area coverage.

Use only one sensor for coverage calculations

---

trollflow2/__init__.py
trollflow2/launcher.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

In the case when there were a crash or all the products were discarded the later plugins were not called. When `FilePublisher` was used, this caused the initialised publisher not to be closed, as the publisher was stopped in the `__call__()` method. With this PR the publisher will be closed when the instance is deleted and garbage collected.

Fix hanging publisher

---

trollflow2/__init__.py

In order to get a realistic daylight coverage estimate of the data, not only the sunlight coverage of the data must be computed, but also the coverage of the pass/actual data. This patch implements this.

Add pass coverage computation to sunlight coverage checking

---

doc/source/conf.py
doc/source/index.rst
examples/docker/config_ears_avhrr/trollflow2_ears_avhrr.yaml
examples/docker/config_ears_viirs/trollflow2_ears_viirs.yaml
examples/docker/config_seviri_hrit/trollflow2_seviri_hrit.yaml
examples/pl.yaml
setup.py
trollflow2/dict_tools.py
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_dict_tools.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds the areas level to the product list, and removes `common`, putting generic configuration at the root of `product_list`.
We also add flexibility to the resolution parameter, which in principle can now be at any level.
TODO:

Add the areas level

---

trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

Introduce the `use_tmp_file` parameter to allow saving the data to a temp file before renaming it to it's final name.
We also included fixes for the previous PR #40

Allow saving files to a temporary name and small fixes

---

.stickler.yml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR implements the sending of dispatch orders to be picked up by another module.
The locations to dispatch to are to be provided in the formats section of the product list.
This PR build on top of #46, so travis might not like this one until #46 is merged.
Example configuration:
```yaml
...
areas:
euron1:
areaname: euron1_in_fname
min_coverage: 20.0
products:
cloud_top_height:
productname: cloud_top_height_in_fname
output_dir: /tmp/satdmz/pps/www/latest_2018/
formats:
- format: png
writer: simple_image
dispatch:
- hostname: ftp.important_client.com
scheme: ftp
username: ic_login
password: very_secure_password
path: "/somewhere/{platform_name:s}_{start_time:%Y%m%d_%H%M}_{areaname:s}_ctth_static.{format}"
- format: jpg
writer: simple_image
fill_value: 0
fname_pattern: …
```

Add dispatch order messages

---

doc/source/index.rst
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

The following syntax is now accepted in the YAML config file:
```yaml
areas:
baws:
areaname: baws
products:
overview_sun:
("1", "2"):
productname: visible_channels
formats:
- format: nc
writer: cf
fname_pattern: "{start_time:%Y%m%d_%H%M}_{platform_name:s}_{productname:s}_{variant:s}.{format}"
```

Allow multiple bands tuple to be passed as a single composite

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR fixes the usage of `coverage_by_collection_area` option. The current version wasn't updated when `areas` level was added to the product list.

Check the area from correct level of the product list

---

examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR allows the addition of arbitrary metadata to the published messages with the `extra_metadata` configuration parameter.

Add the possibility to add extra metadata to the published messages

---

bin/satpy_launcher.py
examples/pl.yaml
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds two command-line options so that `nameserver` and `addresses` can be passed to `ListenerContainer`. With these options it should be possible to run `trollflow2` without multicast.
This also adds `nameservers` kwarg to `FilePublisher` class.

Add "nameserver" and "addresses" command-line options

---

examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR ensures that composites are generated also for `null` areas, i.e. for areas which are saved as-is without resampling.

Ensure composites are generated for scenes without resampling

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR fixes the publisher, which was stopped after the first processed areas. This caused the next area to have `None` as the publisher and a crash.

Fix publisher stopping after first processed area

---

doc/source/index.rst
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

Stop the workers when the process is done

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR fixes the `formats` dictionaries being the same object. This caused all the filenames being the same when a minimal product list without explicitly written `formats` section were used, see below.
```yaml
formats:
- format: tif
writer: geotiff
areas:
euro4:
areaname: euro4
products:
overview:
productname: overview
airmass:
productname: airmass
```

Fix formats dictionary being the same object

---

examples/pl.yaml
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR changes the behaviour of `check_sunlight_coverage()` so that it will use the name of area definitions instead of individual composite/channel areas read from resampled scene attributes. This way the filtering can be done before loading and resampling. If the data are not to be projected (area defined as `null` in the config), the area is read from the dataset attributes and the plugin needs to be after the data is loaded with `load_composites`.
Closes https://github.com/pytroll/pyresample/issues/228

Use area definition names to check sunlight coverage

---

examples/docker/build_dir/Dockerfile_dev
examples/docker/build_dir/Dockerfile_stable

PR fixes the issue with the conda channel priorities by adding arguments to conda install in the dev and stable Dockerfiles
Bug looked like this:
Traceback (most recent call last):
File "/opt/conda/bin/satpy_launcher.py", line 27, in <module>
from trollflow2.launcher import run
File "/opt/conda/lib/python3.7/site-packages/trollflow2/launcher.py", line 45, in <module>
from trollflow2.plugins import AbortProcessing
File "/opt/conda/lib/python3.7/site-packages/trollflow2/plugins/__init__.py", line 31, in <module>
import rasterio
File "/opt/conda/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module>
from rasterio._base import gdal_version
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory

Fix conda channel priority issue

---

trollflow2/plugins/__init__.py

With this PR the imports for GEO bounding box computations are done from Pyresample instead of Satpy. The version there can handle also projections with `ellps` instead of `a/b/h` in the projection definition.

Use get_geostationary_bounding_box from pyresample instead of satpy

---

examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR adds a possibility to call `native` resampler for unprojected (area `None`) scene.

Implement call to native resampler

---

.travis.yml
examples/docker/config_ears_avhrr/trollflow2_ears_avhrr.yaml
setup.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR adds a plugin that can be used to check the sensor given in the message metadata.
This is needed when handling messages coming from `aapp_dr_runner` which basically needs to use the same topics for every sensor.

Add a pluging to check message metadata

---

.travis.yml

Tests are failing on travis because of an old pytest being already installed.

Upgrade packages on travis installation

---

examples/pl.yaml
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR makes it possible to use `dask.distributed` with trollflow2. The example config (below, defined in the trollflow2 config file) uses `dask.distributed.Client` to connect to a scheduler and associated workers. If `dask_distributed` isn't in the configuration, the default scheduler is used. This is hopefully generic enough to meet the idea @djhoese gave in #82 for the user to define their own scheduling/cluster classes.
```yaml
dask_distributed:
class: !!python/name:dask.distributed.Client
settings:
address: localhost:8786
```

Add support to dask.distributed

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Satpy 0.23 privatized the `.datasets` attribute of the scene, and thus broke some parts of trollflow2 that used it. This PR fixes it.

Fix null resampling with newer versions of satpy

---

doc/source/index.rst
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Working with SAR IW data, the data is simply to large to be useful. This plugin gives the possibility to aggregate the data before it's processed further.

Add the aggregate plugin

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR add the functionality of creating a (fsspec) filesystem object to be provided in a `satpy.FSFile` instance to pass to satpy.

Add possibility to provide a jsonified filesystem spec in the message

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

When logging a debug message that an area is kept because of sufficient
area coverage, add the name of the area.
This will break backward compatibility with systems searching for this exact log message.

Add area name to "area kept" log message

---

AUTHORS.md
doc/source/index.rst
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Adapt the trollflow2 `create_scene` plugin for the removal of
ppp_config_dir.  Fixes #96.

Adapt trollflow2 for removal of ppp_config_dir

---

.github/workflows/ci.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR fixes the FilePublisher by looking if a product exists in the resampled scene prior to publishing.

Check that products exist before publishing

---

.github/workflows/ci.yaml

For the unstable build in which satpy is installed without dependencies,
also install pyresample, or importing satpy may fail under some
circumstances.

For unstable build, also install pyresample.

---

bin/satpy_launcher.py
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR fixes the log passing from subprocesses to the main process by using a QueueHandler instead of using the predifined handlers passed on through the forking mechanism. This is the recommended way of doing the logging across processes.
The current implementation is suspected to be at the origin of deadlocks causing trollflow2 processing to stop and hang forever, as observed by @gerritholl and myself.
The runner code and tests were also refactored for cleaning purposes.

Use queued logging for running in subprocesses

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This is part of my slowly ongoing plan on using Trollflow2 in a container on operations. For our (FMI) use case it might be necessary to use direct port connections between different parts of the whole chain (Trollmoves Server -> Trollmoves Client -> segment gatherer -> Trollflow2 -> Georest -> Geoserver) without any of the steps using Posttroll `nameservers`s.
The default (below) usage will still require a Posttroll `nameserver`, and the publisher will default to use the one on `localhost'. By default the publish port is automatically selected
```yaml
workers:
- fun: !!python/object:trollflow2.plugins.FilePublisher {}
```
To use direct port communications without connecting to a `nameserver`:
```yaml
workers:
- fun: !!python/object:trollflow2.plugins.FilePublisher {port=40000, …
```

Make it possible to use `FilePublisher` without running a nameserver

---

trollflow2/tests/test_launcher.py

This PR refactors the test_process method to allow skipping the timeout test properly on MacOS
cc @gerritholl

Fix MacOS timeout test skip

---

bin/satpy_launcher.py
trollflow2/launcher.py
trollflow2/logging.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_logging.py

It has been observed that trollflow2 v0.11.0 hangs quite often, probably due to a race condition in the logging code.
It is very likely that this bug has been introduced in #115, hence this attempt to make the QueueHandler usage more streamlined, independently of whether trollflow2 runs on threads or subprocesses, and more importantly by setting up the queued log handler and other handlers prior to running the main loop.
EDIT: for completeness, it should be noted that many live tests have been run with v0.10.0 at SMHI and that hanging specifically in the logging part was also happening.

Logging fix using global QueueHandler

---

examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Add an option to create the temporary file in a temporary directory, respecting the basename.  This will close #125.  We need this so that the filename passed to the writer and therefore the contents of the filename tag in ninjogeotiff files remains meaningful.

Add flag to create temporary file in temporary directory

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Recent Satpy doesn't have anything in the Scene attributes, so we need to merge input metadata to it. This was already done in most of the plugins, but not in `sza_check`. This PR refactors the tests for this plugin, and implements a fix to the missing start time.

Fix scene attribute usage in sza_check

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

When a product is removed due to insufficient sunlight coverage, include
information about the detected amount of sunlight converage.  This might
help debugging in cases when scenes are unexpectedly removed.
Example of new logging:
```
[2021-12-29 12:30:01,093 INFO     trollflow2.plugins] Not enough sunlight coverage for product 'snow_age', removed. Needs at least 5.0%, got 0.0%.
[2021-12-29 12:30:01,095 INFO     trollflow2.plugins] Not enough sunlight coverage for product 'true_color', removed. Needs at least 5.0%, got 0.0%.
[2021-12-29 12:30:01,098 INFO     trollflow2.plugins] Not enough sunlight coverage for product 'overview', removed. Needs at least 5.0%, got 0.0%.
[2021-12-29 12:30:01,100 INFO     trollflow2.plugins] Not enough sunlight coverage for product …
```

More verbose logging when removing due to lack of sunlight

---

.github/workflows/ci.yaml
setup.py
trollflow2/dict_tools.py
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_dict_tools.py
trollflow2/tests/test_trollflow2.py

We've had a version limitation `dpath<1.5` as it seemed the `.util` sub-package didn't exist after that. That was not the case, and everything works if we do `import dpath.util`. This fixes the imports, and removes the version restriction.
Internally "use satellite projection", which in the product list is marked by using `null` as area name, now uses `'None'` as the newer versions of `dpath` only support string and integer names.

Remove dpath version restriction and fix the import

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

In #134 the config reading was refactored, and the `Loader` kwarg was accidentally changed when the product list is read.

Use UnsafeLoader when reading product list for process()

---

continuous_integration/environment.yaml
setup.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

In Satpy the `Scene` object no longer have metadata in the `.attrs` dictionary. This PR replaces that usage by collecting the relevant items from the `.start_time`, `.end_time` and `.sensor_names` attributes/properties where required.
The required Satpy version is set to `>=0.32.0` to be certain `.sensor_names` attribute is present.

Use scene properties instead of .attrs where needed

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR removes a log warning when the sensor is provided as a sequence of only one element.

Fix warning issued when multiple sensors are provided

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

The PR fixes so that the following data would report 100% sunlight coverage when check_pass is true:

Fix sunlight coverage check to return 100% when the data is fully lit

---

doc/source/index.rst
examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

When saving multiple datasets to a single CF/NetCDF4 file using the syntax introduced in https://github.com/pytroll/trollflow2/pull/51 , I got random crashes resulting in `RuntimeError: NetCDF: Not a valid ID` within the XArray library. Some internet searching suggested that this is due to trying to use dimensions that have not yet been defined.
My solution to this is adding a config option that forces an eager saving instead of delaying the saving and calling `compute_writer_results()` afterwards. With this PR, I haven't seen this happen a single time over 50 consecutive runs.

Make it possible to do eager saving

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

When saving datasets, pop out all keyword arguments that are used by
the trollflow2 save_datasets plugin, but not by writers.
Add unit test to confirm this popping works.

Pop unknown keyword arguments in save_dataset

---

continuous_integration/environment.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Computing the coverage of a dynamic area def does not work at the moment since the bbox can not be computed (understandably).
This fix gives a coverage of 100% for these types of areas.

Do not crash when computing coverage of a dynamic area def

---

doc/source/index.rst
examples/pl.yaml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Allow to configure arbitrary extra parameters to be passed to
Scene.load.

Pass arbitrary params to Scene.load

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

Recent changes in the pytroll-collector package regarding formatting of message for remote filesystems require trollflow2 to adapt. This PR implements the adaptation.

Adapt remote (fsspec) file reading for newer pytroll-collector changes

---

doc/source/index.rst
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

In Satpy, get_min_area and get_max_area are deprecated.  They were still
being used in trollflow2.  Replace this by use_coarsest_area and
use_finest_area.  Update tests and documentation accordingly.  Keep the
old name for backward compatibility.

replace min/max area by finest/coarsest area

---

doc/source/index.rst
trollflow2/plugins/__init__.py

This PR brings support to decompression of MTG/FCI L1 files that have been compressed with JLS compression by trying to import `hdf5plugin` library.
Can't think of any unit tests for this, but I did run actual data through and decompression works after this minor change.

Import hdf5plugin for JLS decompression support if available

---

doc/source/index.rst
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

With this PR it is possible to discard "too old" data before it is processed.
My use-case is the occasional data outages in Eumetacast, where the data are often sent late to make the data series intact. This causes the processing queue to stay full for hours (depending on the outage duration), and delays the processing of current data. With this feature it would be possible to discard the old data.

Add checking for incoming data age

---

.gitignore
trollflow2/tests/test_trollflow2.py

This PR fixes a failing test that is due to pyresample being more strict about lons and lats not being within bounds. The failing test actually exhibited a bug in the test which this PR fixes.

Fix tests for pyresample's spherical update

---

doc/source/index.rst
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR switches the `FilePublisher` plugin to use `create_publisher_from_dict_config()` from Posttroll.
The undocumented feature of turning `nameserver` usage off uses now the same principles that Posttroll:
- use `nameservers: False`
- set `port` to non-zero numeric value

Make it possible to disable nameserver in FilePublisher

---

bin/satpy_launcher.py
doc/source/index.rst
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

It wasn't possible to disable the subscriber nameserver to `False`. With this PR, the argument parsing takes care of this. Also, the argument parsing and launching of the `Runner` have now been moved to `trollflow2.launcher` so we could add tests for them.

Handle setting subscriber nameserver to False

---

.github/workflows/ci.yaml
README.md
doc/source/index.rst
setup.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_logging.py

This PR drops Python 3.8 support from Trollflow2.
The CI is adjusted to test with Python 3.9, 3.10 and 3.11.

Drop Python 3.8 support

---

setup.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR fixes the calls to publisher methods to be inline with the newer version of posttroll, and avoid a hang at the end of the processing.

Fix call to posttroll publishers' start and stop

---

trollflow2/logging.py
trollflow2/tests/test_logging.py
trollflow2/tests/test_trollflow2.py

This PR allows trollflow2 to accept log configs without loggers.

Fix logging to handler config without loggers

---

trollflow2/logging.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_logging.py
trollflow2/tests/test_trollflow2.py

This PR fixes couple of test failures.

Fix test failures

---

.github/workflows/ci.yaml

Update CI to use Python versions 3.10, 3.11 and 3.12.

Update CI to use Python 3.10 - 3.12

---

bin/satpy_launcher.py

Make trollflow2 more multiprocessing / dask-distributed friendly. Move the launcher import in satpy_launcher.py within the main function, so that it only gets executed in the primary process. The call to `Manager()` in `trollflow2.__init__.py` was causing attempts to use trollflow2 with dask distributed to fail with a RuntimeError.
I don't know how to add a unit test for this.

Move import to be dask-dist friendly

---

.github/workflows/ci.yaml

The Mambaforge installer is [deprecated](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/), so lets switch to Miniforge.

Switch from Mambaforge to Miniforge

---

continuous_integration/environment.yaml
setup.py
trollflow2/__init__.py
trollflow2/dict_tools.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This PR aims at reducing warnings emitted when running the tests.
:heavy_check_mark: Needs rebasing after #201 has been merged.

Reduce test warnings

---

doc/source/launcher.rst
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR adds handling for SIGTERM signal, so that Trollflow2 can be terminated gracefully in for example container environment.

Add handling for SIGTERM

---

.pre-commit-config.yaml
.stickler.yml
setup.py
trollflow2/cli.py
trollflow2/launcher.py
trollflow2/tests/test_cli.py
trollflow2/tests/test_launcher.py

This PR adds a command line interface (CLI) to trollflow2.
This allows for easier launching in environments that might not have posttroll messaging enabled or for batch reprocessing.

Add a Command Line Interface

---

trollflow2/cli.py
trollflow2/tests/test_cli.py

For the CLI added in #184, add an option to profile the results using dask.diagnostics and visualize the results as a bokeh plot.

Profile CLI run through dask

---

trollflow2/tests/test_trollflow2.py

The `TestSaveDatasets.test_pop_unknown_args` is creating a Hungarian directory and not removing it. This PR fixes it by using `tmp_path` fixture.

Put output dir to tmp_path

---

.readthedocs.yaml

I noticed in a Dependabot PR that Read the Docs builds were failing due to a missing config item. This PR adds it. For more information, see https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Add Sphinx config path to RTD config

---

doc/source/plugins.rst
doc/source/product_list.rst

This PR removes references to removed plugins from the documentation.

Remove references to removed plugins

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Trollflow2 is printing a log message saying `Loading 1 composites` even when there are more. This PR fixes the log message.

Fix log message printing the number of loaded composites
