trollflow2/__init__.py

This PR fixes so that composites that couldn't be generated won't crash the whole system when saved. Instead, an info will be logged, and the other composites will be saved as they should.

Skip bogus composites to allow saving the rest

---

bin/satpy_launcher.py
examples/pl.yaml
trollflow2/launcher.py
trollflow2/tests/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR makes it possible to prioritize areas to be processed in certain order by giving them priority value. If priorities are not given, all defined areas are processed together. All areas with the same priority are processed together.

Add possibility to prioritize production by area

---

trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR expand minimal product lists, and propagates formats to the product level.

Expand minimal product lists before processing

---

trollflow2/tests/test_launcher.py

This PR adds some tests that were missing for `launcher.process`.

Add actual tests for launcher.process()

---

trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

This allows the correct usage of keys vs names for areas and products

Fix plist_iter to provide the area and product keys too

---

bin/satpy_launcher.py
examples/pl.yaml
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

This PR adds a possibility to configure topics for the subscribed message in config file in addition to command line.

Add a possibility to define subscribe topics in config file

---

trollflow2/__init__.py

Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>

Handle the situation when data is not covering the area at all

---

trollflow2/__init__.py
trollflow2/tests/test_trollflow2.py

Handle the situation when a product/dataset is not loaded due to insufficient spectral bands available
Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>

Handle gracefully the situation when a dataset is not loaded

---

trollflow2/plugins/__init__.py

This PR removes a print statement and fixes 3 styling issues.

Remove print statement

---

.stickler.yml
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Ensure empty tmp files aren't kept and that only valid files are renamed.

Make writing via tmp file more robust

---

.travis.yml

Switch to pytest and add codecov reports

Switch to pytest and add codecov reports

---

trollflow2/plugins/__init__.py

Added area, areaname, product, productname, area_coverage_percent, area_sunlight_coverage_percent, format.

Add some metadata to the published file messages

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
AUTHORS.md
RELEASING.md
trollflow2/_version.py
trollflow2/dict_tools.py
trollflow2/launcher.py
trollflow2/tests/__init__.py
trollflow2/tests/test_dict_tools.py
trollflow2/tests/test_launcher.py
trollflow2/tests/utils.py

Also, the test suites were removed as pytest doesn't need them.

Add GitHub templates and make flake8 happy

---

bin/satpy_launcher.py

Add the possibility to provide a log config to satpy_laucher.py

---

bin/satpy_launcher.py
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

This PR adds checks if the composites are actually produced when the process is over

Check if the composites are actually produced when the trollflow2 process is over

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Can be useful for night composites

Add max daylight coverage feature

---

doc/source/index.rst

This PR adds documentation on the various Trollflow2 plugins.

Document plugins

---

doc/source/index.rst

There were some formatting errors in #75 which this PR fixes

Fix RST formatting

---

setup.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Replace usage of DatasetID by DataQuery for newer satpy versions

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

This is the second part of #86 , missed it as I didn't think if fixing the tests accordingly. This is done in this PR.

Fix dataquery defaults

---

trollflow2/plugins/__init__.py
trollflow2/tests/test_trollflow2.py

Fix a default resolution bug making satpy 0.23 crash

---

trollflow2/tests/test_launcher.py

Well, that's what it costs not to run tests in github before merging...

Fix fsfile-induced test failures

---

trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_launcher.py
trollflow2/tests/test_trollflow2.py

Adjust message levels and wordings

---

.github/workflows/ci.yaml
continuous_integration/environment.yaml
setup.py
trollflow2/dict_tools.py
trollflow2/launcher.py
trollflow2/plugins/__init__.py
trollflow2/tests/test_dict_tools.py
trollflow2/tests/test_trollflow2.py

Drop Python 3.7 from the tested Python versions and add Python 3.10.
The test environments are now built using Mambaforge.

Change tested Python versions to 3.8, 3.9 and 3.10

---

.readthedocs.yaml

This PR adds a .readthedocs.yaml file

Add a .readthedocs.yaml file

---

.readthedocs.yaml

This is still an attempt to fix rtd

Add os in the .readthedocs.yaml file

---

AUTHORS.md
setup.py
trollflow2/launcher.py
trollflow2/tests/test_launcher.py

Only yield msgs with valid msg types in generate_messages

---

trollflow2/tests/test_trollflow2.py

This PR fixes the tests for the upcoming posttroll changes.

Fix tests for upcoming posttroll version

---

AUTHORS.md
examples/docker/build_dir/Dockerfile_dev
examples/docker/build_dir/Dockerfile_stable

Changing from pyinotify to watchdog and forcing dask version for numpy 2.0 compatibility
